# -*- coding: utf-8 -*-
"""administrador

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g488IU6rM3s05fKdSlCArEqH8HMSYaPx

Administrador
"""

# ============================================================
#  MÓDULO DE ADMINISTRACIÓN
# ============================================================

from usuarios import leer_usuarios, buscar_usuario
from reservas import leer_reservas
from funciones import leer_funciones, ordenar_funciones
from asientos import cargar_asientos

# Credenciales de administrador
ADMIN_USER = "admin"
ADMIN_PASS = "admin123"


# ------------------------------------------------------------
#  MÓDULO PRINCIPAL DEL ADMINISTRADOR
# ------------------------------------------------------------
def admin():
    print("\n=== ADMINISTRACIÓN ===")

    u = input("Usuario: ")
    p = input("Contraseña: ")

    if u != ADMIN_USER or p != ADMIN_PASS:
        print("Acceso denegado.")
        return

    reservas = leer_reservas()
    usuarios = leer_usuarios()

    # -------------------------
    # LISTA DE USUARIOS
    # -------------------------
    print("\n--- LISTA DE USUARIOS REGISTRADOS ---")
    for u in usuarios:
        print(f"{u['documento']} - {u['nombre']} {u['apellido']} ({u['vinculo']})")

    # -------------------------
    # REPORTES GENERALES
    # -------------------------
    total_reservas = len(reservas)
    total_pago = sum(int(r["precio"]) for r in reservas)
    promedio_diario = total_pago / 3 if total_pago > 0 else 0

    print("\n--- REPORTES GENERALES ---")
    print("Total de reservas realizadas:", total_reservas)
    print("Total pagado:", total_pago)
    print("Promedio diario del cine:", round(promedio_diario, 2))

    # -------------------------
    # USUARIO CON MÁS Y MENOS RESERVAS
    # -------------------------
    conteo = {}
    for r in reservas:
        conteo[r["documento"]] = conteo.get(r["documento"], 0) + 1

    if conteo:
        mayor = max(conteo, key=conteo.get)
        menor = min(conteo, key=conteo.get)

        u_mayor = buscar_usuario(mayor)
        u_menor = buscar_usuario(menor)

        print("\nUsuario con MÁS reservas:",
              u_mayor["nombre"], u_mayor["apellido"], "→", conteo[mayor])

        print("Usuario con MENOS reservas:",
              u_menor["nombre"], u_menor["apellido"], "→", conteo[menor])

    # -------------------------
    # DISPONIBILIDAD POR FUNCIÓN
    # -------------------------
    print("\n--- DISPONIBILIDAD POR FUNCIÓN ---")
    for f in ordenar_funciones(leer_funciones()):
        mapa = cargar_asientos(f["function_id"])
        libres = sum(1 for s in mapa if s["estado"] == "O")
        print(f"{f['function_id']} | {f['titulo']} | {f['dia']} {f['hora']} | Disponibles: {libres}")