# -*- coding: utf-8 -*-
"""administrador

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QbjZ_v3aidb3x0qz_wBSjanPMY7taz6w
"""

#============================================================
#  ADMINISTRADOR
# ============================================================

ADMIN_USER = "admin"
ADMIN_PASS = "admin123"

def admin():
    print("\n=== ADMINISTRACIÓN ===")

    u = input("Usuario: ")
    p = input("Contraseña: ")

    if u != ADMIN_USER or p != ADMIN_PASS:
        print("Acceso denegado.")
        return

    reservas = leer_reservas()
    usuarios = leer_usuarios()

    print("\n--- LISTA DE USUARIOS ---")
    for u in usuarios:
        print(f"{u['documento']} - {u['nombre']} {u['apellido']} ({u['vinculo']})")

    total = len(reservas)
    total_pago = sum(int(r["precio"]) for r in reservas)
    promedio_diario = total_pago / 3 if total else 0

    print("\n--- REPORTES GENERALES ---")
    print("Total de reservas:", total)
    print("Total pagado:", total_pago)
    print("Promedio diario:", round(promedio_diario,2))

    conteo = {}
    for r in reservas:
        conteo[r["documento"]] = conteo.get(r["documento"],0) + 1

    if conteo:
        mayor = max(conteo, key=conteo.get)
        menor = min(conteo, key=conteo.get)
        u1 = buscar_usuario(mayor)
        u2 = buscar_usuario(menor)

        print("\nUsuario con más reservas:", u1["nombre"], u1["apellido"], "→", conteo[mayor])
        print("Usuario con menos reservas:", u2["nombre"], u2["apellido"], "→", conteo[menor])

    print("\n--- DISPONIBILIDAD POR FUNCIÓN ---")
    for f in ordenar_funciones(leer_funciones()):
        mapa = cargar_asientos(f["function_id"])
        libres = sum(1 for s in mapa if s["estado"] == "O")
        print(f"{f['function_id']} | {f['titulo']} | {f['dia']} {f['hora']} | Disponibles: {libres}")


# ============================================================
#  MENÚ PRINCIPAL
# ============================================================

def main():
    asegurar_archivos()
    cargar_funciones_iniciales()

    for f in leer_funciones():
        inicializar_asientos(f["function_id"], f["disponibles"])

    while True:
        titulo_filmoteca()

        print("1. Registrar Usuario")
        print("2. Registrar Reserva")
        print("3. Cancelar Reserva")
        print("4. Consultar Funciones")
        print("5. Administrador")
        print("6. Salir")

        opcion = input("\nSeleccione una opción: ")

        if opcion == "1":
            registrar_usuario()
        elif opcion == "2":
            registrar_reserva()
        elif opcion == "3":
            cancelar_reserva()
        elif opcion == "4":
            mostrar_cartelera()
        elif opcion == "5":
            admin()
        elif opcion == "6":
            print("\nGracias por usar Filmoteca 121 UdeA 💚\n")
            break
        else:
            print("Opción inválida.")

        input("\nPresione ENTER para continuar...")

main()