# -*- coding: utf-8 -*-
"""administrador

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y9B6IkfkPZTMQ7FbEoCPJdS9lzURc-q2
"""
USERS_FILE = "users.csv"
RES_FILE = "reservas.csv"
FUNC_FILE = "funciones.csv"

import csv

# ============================================================
# IMPORTS NECESARIOS
# ============================================================

# usuarios.py
from usuarios import leer_usuarios, buscar_usuario

# reservas.py
from reservas import leer_reservas

# funciones.py
from funciones import ordenar_funciones, leer_funciones

# asientos.py
from asientos import cargar_asientos


# ============================================================
#  ADMINISTRADOR
# ============================================================

ADMIN_USER = "admin"
ADMIN_PASS = "admin123"


def admin():
    print("\n=== ADMINISTRACIÓN ===")
    u = input("Usuario: ").strip()
    p = input("Contraseña: ").strip()

    if u != ADMIN_USER or p != ADMIN_PASS:
        print("Acceso denegado.")
        return

    reservas = leer_reservas()
    usuarios = leer_usuarios()

    print("\n--- LISTA DE USUARIOS ---")
    for uu in usuarios:
        print(f"{uu['documento']} - {uu['nombre']} {uu['apellido']} ({uu['vinculo']})")

    total = len(reservas)
    total_pago = sum(int(r["precio"]) for r in reservas) if reservas else 0
    promedio_diario = total_pago / 3 if total else 0

    print("\n--- REPORTES GENERALES ---")
    print("Total de reservas:", total)
    print("Total pagado:", total_pago)
    print("Promedio diario:", round(promedio_diario, 2))

    # Conteo por usuario
    conteo = {}
    for r in reservas:
        conteo[r["documento"]] = conteo.get(r["documento"], 0) + 1

    if conteo:
        mayor = max(conteo, key=conteo.get)
        menor = min(conteo, key=conteo.get)
        u1 = buscar_usuario(mayor)
        u2 = buscar_usuario(menor)
        if u1:
            print("\nUsuario con más reservas:", u1["nombre"], u1["apellido"], "→", conteo[mayor])
        if u2:
            print("Usuario con menos reservas:", u2["nombre"], u2["apellido"], "→", conteo[menor])

    print("\n--- DISPONIBILIDAD POR FUNCIÓN ---")
    for f in ordenar_funciones(leer_funciones()):
        mapa = cargar_asientos(f["function_id"])
        libres = sum(1 for s in mapa if s["estado"] == "O")
        print(f"{f['function_id']} | {f['titulo']} | {f['dia']} {f['hora']} | Disponibles: {libres}")
