# -*- coding: utf-8 -*-
"""archivos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y9B6IkfkPZTMQ7FbEoCPJdS9lzURc-q2
"""
import os
import csv

# ============================================================
#  ARCHIVOS
# ============================================================

USERS_FILE = "users.csv"
RES_FILE = "reservas.csv"
FUNC_FILE = "funciones.csv"

def asegurar_archivos():
    if not os.path.exists(USERS_FILE):
        with open(USERS_FILE, "w", newline="", encoding="utf-8") as f:
            f.write("documento,nombre,apellido,vinculo\n")

    if not os.path.exists(RES_FILE):
        with open(RES_FILE, "w", newline="", encoding="utf-8") as f:
            f.write("idreserva,documento,function_id,asiento,precio,fecha\n")

    if not os.path.exists(FUNC_FILE):
        with open(FUNC_FILE, "w", newline="", encoding="utf-8") as f:
            f.write("function_id,movie_id,titulo,dia,hora,disponibles\n")
