# -*- coding: utf-8 -*-
"""asientos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xO6RvuBXgjxqEbdy7qZjlo5hEBcUwUAd
"""

# ============================================================
#  ASIENTOS
# ============================================================

FILAS = [chr(i) for i in range(ord('A'), ord('A') + 11)]  # A..K (11 filas)
COLUMNAS = list(range(1, 12))  # 1..11

def archivo_asientos(fid):
    return f"asientos_{fid}.csv"

def inicializar_asientos(fid, disponibles):
    """Crea archivo de asientos para la función si no existe.
    'disponibles' puede venir como string desde el CSV por eso lo convertimos a int."""
    fname = archivo_asientos(fid)
    if os.path.exists(fname):
        return

    try:
        disp_int = int(disponibles)
    except Exception:
        disp_int = 100  # fallback

    total = len(FILAS) * len(COLUMNAS)
    ocupados = total - disp_int
    if ocupados < 0:
        ocupados = 0

    asientos = []
    for i, fila in enumerate(FILAS):
        for c in COLUMNAS:
            pos = i * len(COLUMNAS) + (c - 1)
            estado = "X" if pos < ocupados else "O"
            asientos.append([f"{fila}{c}", estado])

    with open(fname, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["asiento","estado"])
        w.writerows(asientos)

def cargar_asientos(fid):
    """Lee y devuelve lista de dicts con campos 'asiento','estado'.
    Si no existe inicializa con 100 libres por defecto."""
    fname = archivo_asientos(fid)
    if not os.path.exists(fname):
        inicializar_asientos(fid, 100)

    with open(fname, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))

def guardar_asientos(fid, filas):
    fname = archivo_asientos(fid)
    with open(fname, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=["asiento","estado"])
        w.writeheader()
        w.writerows(filas)

def mostrar_asientos(fid):
    print("\n     MAPA DE ASIENTOS (O = Libre, X = Ocupado)\n")
    mapa = cargar_asientos(fid)
    dic = {s["asiento"]: s["estado"] for s in mapa}

    # cabecera de columnas
    print("    "+" ".join([f"{c:>2}" for c in COLUMNAS]))
    for fila_letra in FILAS:
        fila_line = f"{fila_letra} | " + " ".join(dic.get(f"{fila_letra}{c}", " ") for c in COLUMNAS)
        print(fila_line)