# -*- coding: utf-8 -*-
"""asientos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g488IU6rM3s05fKdSlCArEqH8HMSYaPx

Asientos
"""

# ============================================================
#  MÓDULO DE ASIENTOS
# ============================================================

import csv
import os
from datos import FILAS, COLUMNAS


# ------------------------------------------------------------
#  ARCHIVO DE ASIENTOS
# ------------------------------------------------------------
def archivo_asientos(fid):
    """Retorna el nombre del archivo CSV para una función."""
    return f"asientos_{fid}.csv"


# ------------------------------------------------------------
#  INICIALIZAR ASIENTOS (solo la primera vez)
# ------------------------------------------------------------
def inicializar_asientos(fid, disponibles):
    """
    Crea el archivo de asientos si no existe, marcando X los que ya están ocupados.
    """
    fname = archivo_asientos(fid)

    if os.path.exists(fname):
        return  # Ya existe, no lo borres

    total_asientos = len(FILAS) * len(COLUMNAS)
    ocupados = total_asientos - int(disponibles)

    asientos = []
    pos_global = 0

    for fila in FILAS:
        for c in COLUMNAS:
            estado = "X" if pos_global < ocupados else "O"
            asientos.append([f"{fila}{c}", estado])
            pos_global += 1

    # Guardar archivo
    with open(fname, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["asiento", "estado"])
        w.writerows(asientos)


# ------------------------------------------------------------
#  CARGAR ASIENTOS
# ------------------------------------------------------------
def cargar_asientos(fid):
    """Carga los asientos de un archivo CSV, inicializando si no existe."""
    fname = archivo_asientos(fid)

    if not os.path.exists(fname):
        inicializar_asientos(fid, 100)

    with open(fname, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


# ------------------------------------------------------------
#  GUARDAR ASIENTOS
# ------------------------------------------------------------
def guardar_asientos(fid, filas):
    """Guarda el estado actual de asientos en el archivo correspondiente."""
    fname = archivo_asientos(fid)

    with open(fname, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=["asiento", "estado"])
        w.writeheader()
        w.writerows(filas)


# ------------------------------------------------------------
#  MOSTRAR MAPA DE ASIENTOS
# ------------------------------------------------------------
def mostrar_asientos(fid):
    """Imprime un mapa visual de asientos 10x11."""
    print("\n     MAPA DE ASIENTOS (O = Libre, X = Ocupado)\n")

    mapa = cargar_asientos(fid)
    dic = {s["asiento"]: s["estado"] for s in mapa}

    # Encabezados
    print("    " + " ".join([f"{c:>2}" for c in COLUMNAS]))

    for f in FILAS:
        fila = f"{f} | " + " ".join(dic[f"{f}{c}"] for c in COLUMNAS)
        print(fila)