# -*- coding: utf-8 -*-
"""asientos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xO6RvuBXgjxqEbdy7qZjlo5hEBcUwUAd
"""

import csv
import os

FILAS = [chr(i) for i in range(ord("A"), ord("A") + 11)]
COLUMNAS = list(range(1, 12))

def archivo_asientos(fid):
    return f"asientos_{fid}.csv"

def inicializar_asientos(fid, disponibles):
    fname = archivo_asientos(fid)
    if os.path.exists(fname):
        return

    try:
        disp_int = int(disponibles)
    except:
        disp_int = 100

    total = len(FILAS) * len(COLUMNAS)
    ocupados = max(0, total - disp_int)

    asientos = []
    for i, fila in enumerate(FILAS):
        for c in COLUMNAS:
            pos = i * len(COLUMNAS) + (c - 1)
            estado = "X" if pos < ocupados else "O"
            asientos.append([f"{fila}{c}", estado])

    with open(fname, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["asiento", "estado"])
        w.writerows(asientos)

def cargar_asientos(fid):
    fname = archivo_asientos(fid)
    if not os.path.exists(fname):
        inicializar_asientos(fid, 100)

    with open(fname, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))

def guardar_asientos(fid, filas):
    fname = archivo_asientos(fid)
    with open(fname, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=["asiento", "estado"])
        w.writeheader()
        w.writerows(filas)

def mostrar_asientos(fid):
    print("\n     MAPA DE ASIENTOS (O = Libre, X = Ocupado)\n")
    mapa = cargar_asientos(fid)
    dic = {s["asiento"]: s["estado"] for s in mapa}

    print("    " + " ".join(f"{c:>2}" for c in COLUMNAS))
    for fila in FILAS:
        print(f"{fila} | " + " ".join(dic[f"{fila}{c}"] for c in COLUMNAS))