# -*- coding: utf-8 -*-
"""cancelar

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g488IU6rM3s05fKdSlCArEqH8HMSYaPx

Cancelar
"""

# ============================================================
#  MÓDULO DE CANCELACIÓN DE RESERVAS
# ============================================================

import csv
from datos import RES_FILE
from usuarios import buscar_usuario
from reservas import leer_reservas
from asientos import cargar_asientos, guardar_asientos


# ------------------------------------------------------------
#  CANCELAR UNA RESERVA
# ------------------------------------------------------------
def cancelar_reserva():
    print("\n=== CANCELAR RESERVA ===")

    doc = input("Documento: ").strip()

    user = buscar_usuario(doc)
    if not user:
        print("⚠️ Usuario no registrado.")
        return

    # Obtener reservas del usuario
    reservas = leer_reservas()
    mis_res = [r for r in reservas if r["documento"] == doc]

    if not mis_res:
        print("Este usuario no tiene reservas activas.")
        return

    # Mostrar reservas del usuario
    print("\nReservas activas:")
    for r in mis_res:
        print(f" - {r['idreserva']} | Función {r['function_id']} | Asiento {r['asiento']}")

    rid = input("\nID de reserva a cancelar: ").strip()

    target = next((r for r in mis_res if r["idreserva"] == rid), None)

    if not target:
        print("ID inválido.")
        return

    # Recuperar mapa de asientos
    mapa = cargar_asientos(target["function_id"])

    # Liberar asiento
    for s in mapa:
        if s["asiento"] == target["asiento"]:
            s["estado"] = "O"

    guardar_asientos(target["function_id"], mapa)

    # Guardar nuevas reservas eliminando la cancelada
    nuevas = [r for r in reservas if r["idreserva"] != rid]

    with open(RES_FILE, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(
            f,
            fieldnames=["idreserva", "documento", "function_id", "asiento", "precio", "fecha"]
        )
        w.writeheader()
        w.writerows(nuevas)

    print("\n✔ Reserva cancelada exitosamente.")