# -*- coding: utf-8 -*-
"""cancelar

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xO6RvuBXgjxqEbdy7qZjlo5hEBcUwUAd
"""

import csv
from datos import RES_FILE
from reservas_facturacion import leer_reservas
from asientos import cargar_asientos, guardar_asientos
from utilidades import solicitar_documento_input

def cancelar_reserva():
    print("\n=== CANCELAR RESERVA ===")

    doc = solicitar_documento_input("Documento del usuario: ")
    reservas = leer_reservas()
    mis_res = [r for r in reservas if r["documento"] == doc]

    if not mis_res:
        print("No tiene reservas.")
        return

    print("\nN° | Función | Asiento | ID Reserva")
    print("-----------------------------------")
    for i, r in enumerate(mis_res, 1):
        print(f"{i} | {r['function_id']} | {r['asiento']} | {r['idreserva']}")

    num = input("Seleccione número de reserva: ")
    if not num.isdigit():
        print("Opción inválida.")
        return

    num = int(num)
    if not (1 <= num <= len(mis_res)):
        print("Número inválido.")
        return

    target = mis_res[num - 1]

    mapa = cargar_asientos(target["function_id"])
    for s in mapa:
        if s["asiento"] == target["asiento"]:
            s["estado"] = "O"
    guardar_asientos(target["function_id"], mapa)

    nuevas = [r for r in reservas if r["idreserva"] != target["idreserva"]]
    with open(RES_FILE, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=["idreserva","documento","function_id","asiento","precio","fecha"])
        w.writeheader()
        w.writerows(nuevas)

    print("\n✔ Reserva cancelada exitosamente.")