# -*- coding: utf-8 -*-
"""cartelera

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g488IU6rM3s05fKdSlCArEqH8HMSYaPx

Cartelera
"""

# ============================================================
#  MÓDULO DE IMPRESIÓN DE CARTELERA
# ============================================================

from funciones import leer_funciones, ordenar_funciones


# ------------------------------------------------------------
#  MOSTRAR CARTELERA COMPLETA
# ------------------------------------------------------------
def mostrar_cartelera():
    """Imprime la cartelera en consola con formato."""
    funcs = ordenar_funciones(leer_funciones())

    print("\n================ CARTELERA DE FILMOTECA 121 UDEA ================\n")

    titulos = sorted(set(f["titulo"] for f in funcs))

    print(f"🎞️ Total de funciones programadas: {len(funcs)}")
    print(f"📽️ Películas en cartelera: {len(titulos)}\n")

    print("PELÍCULAS DISPONIBLES:")
    for t in titulos:
        print(" -", t)

    print("\nHORARIOS Y DISPONIBILIDAD:")
    print("---------------------------------------------------------------")
    print(f"{'ID':<6} {'Día':<10} {'Hora':<6} {'Película':<25} {'Disp':>5}")

    for f in funcs:
        print(f"{f['function_id']:<6} {f['dia']:<10} {f['hora']:<6} {f['titulo']:<25} {f['disponibles']:>5}")