# -*- coding: utf-8 -*-
"""cartelera

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xO6RvuBXgjxqEbdy7qZjlo5hEBcUwUAd
"""

from funciones import leer_funciones

dias_orden = ["Viernes", "Sábado", "Domingo"]

def ordenar_funciones(funcs):
    def key_fun(f):
        hora = int(f["hora"].replace("pm","").replace("am",""))
        return (dias_orden.index(f["dia"]), hora)
    return sorted(funcs, key=key_fun)

def mostrar_cartelera():
    funcs = ordenar_funciones(leer_funciones())

    print("\n================ CARTELERA DE FILMOTECA 121 UDE A ================\n")
    titulos = sorted(set(f["titulo"] for f in funcs))

    print(f"🎞️ Total de funciones programadas: {len(funcs)}")
    print(f"📽️ Películas en cartelera: {len(titulos)}\n")

    print("PELÍCULAS DISPONIBLES:")
    for t in titulos:
        print(" -", t)

    print("\nHORARIOS Y DISPONIBILIDAD:")
    print(f"{'ID':<6} {'Día':<10} {'Hora':<6} {'Película':<25} {'Disp':>5}")

    for f in funcs:
        print(f"{f['function_id']:<6} {f['dia']:<10} {f['hora']:<6} {f['titulo']:<25} {f['disponibles']:>5}")