# -*- coding: utf-8 -*-
"""datos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xO6RvuBXgjxqEbdy7qZjlo5hEBcUwUAd
"""

import os

USERS_FILE = "users.csv"
RES_FILE = "reservas.csv"
FUNC_FILE = "funciones.csv"

TARIFAS = {
    "Estudiantes": 7500,
    "Docentes": 10000,
    "Administrativos": 8500,
    "Oficiales internos": 7000,
    "Publico externo": 15000
}

VINCULOS = list(TARIFAS.keys())

def asegurar_archivos():
    if not os.path.exists(USERS_FILE):
        with open(USERS_FILE, "w", newline="", encoding="utf-8") as f:
            f.write("documento,nombre,apellido,vinculo\n")

    if not os.path.exists(RES_FILE):
        with open(RES_FILE, "w", newline="", encoding="utf-8") as f:
            f.write("idreserva,documento,function_id,asiento,precio,fecha\n")

    if not os.path.exists(FUNC_FILE):
        with open(FUNC_FILE, "w", newline="", encoding="utf-8") as f:
            f.write("function_id,movie_id,titulo,dia,hora,disponibles\n")