# -*- coding: utf-8 -*-
"""datos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g488IU6rM3s05fKdSlCArEqH8HMSYaPx

DATOS
"""

# ============================================================
#  DATOS GENERALES Y ARCHIVOS DEL SISTEMA
# ============================================================

import os

# Archivos CSV usados por todo el sistema
USERS_FILE = "users.csv"
RES_FILE = "reservas.csv"
FUNC_FILE = "funciones.csv"

# Tarifas por tipo de vínculo
TARIFAS = {
    "Estudiantes": 7500,
    "Docentes": 10000,
    "Administrativos": 8500,
    "Oficiales internos": 7000,
    "Publico externo": 15000
}

# IDs para funciones y películas
FUNC_IDS = ["F01","F02","F03","F04","F05","F06","F07","F08","F09"]
MOV_IDS = ["M01","M02","M03"]

# Orden de días
dias_orden = ["Viernes", "Sábado", "Domingo"]

# Asientos disponibles (mapa 10x11)
FILAS = [chr(i) for i in range(ord('A'), ord('A') + 11)]
COLUMNAS = list(range(1, 12))

def asegurar_archivos():
    """Crea los archivos iniciales si no existen."""
    if not os.path.exists(USERS_FILE):
        with open(USERS_FILE, "w", newline="", encoding="utf-8") as f:
            f.write("documento,nombre,apellido,vinculo\n")

    if not os.path.exists(RES_FILE):
        with open(RES_FILE, "w", newline="", encoding="utf-8") as f:
            f.write("idreserva,documento,function_id,asiento,precio,fecha\n")

    if not os.path.exists(FUNC_FILE):
        with open(FUNC_FILE, "w", newline="", encoding="utf-8") as f:
            f.write("function_id,movie_id,titulo,dia,hora,disponibles\n")