# -*- coding: utf-8 -*-
"""funciones

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g488IU6rM3s05fKdSlCArEqH8HMSYaPx

Funciones
"""

# ============================================================
#  MÓDULO DE FUNCIONES (CARTELERA BASE)
# ============================================================

import csv
from datos import FUNC_FILE, FUNC_IDS, MOV_IDS, dias_orden


# ------------------------------------------------------------
#  LECTURA DE FUNCIONES
# ------------------------------------------------------------
def leer_funciones():
    """Lee todas las funciones desde el archivo CSV."""
    with open(FUNC_FILE, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


# ------------------------------------------------------------
#  CARGAR FUNCIONES INICIALES SOLO LA PRIMERA VEZ
# ------------------------------------------------------------
def cargar_funciones_iniciales():
    """Carga automáticamente las 9 funciones si no existen aún."""
    if leer_funciones():
        return  # Ya existen, no volver a crear

    peliculas = [
        ("M01", "Interstellar", [
            ("Viernes", "2pm", 100),
            ("Viernes", "4pm", 5),
            ("Viernes", "6pm", 50)
        ]),

        ("M02", "Oppenheimer", [
            ("Sábado", "2pm", 23),
            ("Sábado", "4pm", 44),
            ("Sábado", "6pm", 66)
        ]),

        ("M03", "The Imitation Game", [
            ("Domingo", "2pm", 11),
            ("Domingo", "4pm", 0),
            ("Domingo", "6pm", 7)
        ])
    ]

    idx = 0
    with open(FUNC_FILE, "a", newline="", encoding="utf-8") as f:
        w = csv.writer(f)

        for mid, titulo, horarios in peliculas:
            for dia, hora, disp in horarios:
                fid = FUNC_IDS[idx]
                idx += 1
                w.writerow([fid, mid, titulo, dia, hora, disp])


# ------------------------------------------------------------
#  ORDENAR FUNCIONES SEGÚN DÍA Y HORA
# ------------------------------------------------------------
def ordenar_funciones(funcs):
    """Ordena funciones por día y hora."""
    def key_fun(f):
        # Orden por día
        dia_index = dias_orden.index(f["dia"])
        # Extraer número de hora
        hora_num = int(f["hora"].replace("pm", "").replace("am", ""))

        return (dia_index, hora_num)

    return sorted(funcs, key=key_fun)