# -*- coding: utf-8 -*-
"""funciones

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y9B6IkfkPZTMQ7FbEoCPJdS9lzURc-q2
"""
import csv
import os

# ============================================================
#  FUNCIONES (CARTELERA)
# ============================================================

FUNC_IDS = ["F01","F02","F03","F04","F05","F06","F07","F08","F09"]
MOV_IDS = ["M01","M02","M03"]
dias_orden = ["Viernes", "Sábado", "Domingo"]

def leer_funciones():
    with open(FUNC_FILE, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))

def cargar_funciones_iniciales():
    """Carga un ejemplo de funciones si el archivo está vacío."""
    if leer_funciones():
        return

    peliculas = [
        ("M01","Interstellar",[("Viernes","2pm",100),
                               ("Viernes","4pm",5),
                               ("Viernes","6pm",50)]),

        ("M02","Oppenheimer",[("Sábado","2pm",23),
                              ("Sábado","4pm",44),
                              ("Sábado","6pm",66)]),

        ("M03","The Imitation Game",[("Domingo","2pm",11),
                                     ("Domingo","4pm",0),
                                     ("Domingo","6pm",7)])
    ]

    idx = 0
    with open(FUNC_FILE, "a", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        for mid, titulo, horarios in peliculas:
            for dia, hora, disp in horarios:
                fid = FUNC_IDS[idx]
                idx += 1
                w.writerow([fid, mid, titulo, dia, hora, disp])

def ordenar_funciones(funcs):
    def key_fun(f):
        # convierte hora "2pm" a número 2 para ordenar; asume formato simple
        hora_num = int(f["hora"].replace("pm","").replace("am",""))
        return (dias_orden.index(f["dia"]), hora_num)
    return sorted(funcs, key=key_fun)

def mostrar_cartelera():
    funcs = ordenar_funciones(leer_funciones())

    print("\n================ CARTELERA DE FILMOTECA 121 UDE A ================\n")

    titulos = sorted(set(f["titulo"] for f in funcs))

    print(f"🎞️ Total de funciones programadas: {len(funcs)}")
    print(f"📽️ Películas en cartelera: {len(titulos)}\n")

    print("PELÍCULAS DISPONIBLES:")
    for t in titulos:
        print(" -", t)

    print("\nHORARIOS Y DISPONIBILIDAD:")
    print("---------------------------------------------------------------")
    print(f"{'ID':<6} {'Día':<10} {'Hora':<6} {'Película':<25} {'Disp':>5}")

    for f in funcs:
        print(f"{f['function_id']:<6} {f['dia']:<10} {f['hora']:<6} {f['titulo']:<25} {f['disponibles']:>5}")
