# -*- coding: utf-8 -*-
"""funciones

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xO6RvuBXgjxqEbdy7qZjlo5hEBcUwUAd
"""

import csv
from datos import FUNC_FILE
from cartelera import dias_orden

def leer_funciones():
    with open(FUNC_FILE, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))