# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xO6RvuBXgjxqEbdy7qZjlo5hEBcUwUAd
"""

from utilidades import titulo_filmoteca
from datos import asegurar_archivos
from funciones import leer_funciones
from asientos import inicializar_asientos
from usuarios import registrar_usuario
from reservas_facturacion import registrar_reserva
from cancelar import cancelar_reserva
from cartelera import mostrar_cartelera
from administrador import admin

def main():
    asegurar_archivos()

    for f in leer_funciones():
        inicializar_asientos(f["function_id"], f["disponibles"])

    while True:
        titulo_filmoteca()
        print("1. Registrar Usuario")
        print("2. Registrar Reserva")
        print("3. Cancelar Reserva")
        print("4. Consultar Funciones")
        print("5. Administrador")
        print("6. Salir")

        op = input("Seleccione: ")

        if op == "1":
            registrar_usuario()
        elif op == "2":
            registrar_reserva()
        elif op == "3":
            cancelar_reserva()
        elif op == "4":
            mostrar_cartelera()
        elif op == "5":
            admin()
        elif op == "6":
            print("Gracias por usar Filmoteca 121 UdeA 💚")
            break
        else:
            print("Opción inválida.")

        input("\nENTER para continuar...")

main()