# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y9B6IkfkPZTMQ7FbEoCPJdS9lzURc-q2
"""
# ============================================================
#  MENÚ PRINCIPAL
# ============================================================

def main():
    asegurar_archivos()
    cargar_funciones_iniciales()

    for f in leer_funciones():
        inicializar_asientos(f["function_id"], f["disponibles"])

    while True:
        titulo_filmoteca()

        print("1. Registrar Usuario")
        print("2. Registrar Reserva")
        print("3. Cancelar Reserva")
        print("4. Consultar Funciones")
        print("5. Administrador")
        print("6. Salir")

        opcion = input("\nSeleccione una opción: ")

        if opcion == "1":
            registrar_usuario()
        elif opcion == "2":
            registrar_reserva()
        elif opcion == "3":
            cancelar_reserva()
        elif opcion == "4":
            mostrar_cartelera()
        elif opcion == "5":
            admin()
        elif opcion == "6":
            print("\nGracias por usar Filmoteca 121 UdeA 💚\n")
            break
        else:
            print("Opción inválida.")

        input("\nPresione ENTER para continuar...")

main()
