# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g488IU6rM3s05fKdSlCArEqH8HMSYaPx

Main
"""

# ============================================================
#  ARCHIVO PRINCIPAL - SISTEMA FILMOTECA 121 UDEA
# ============================================================

from datos import asegurar_archivos
from funciones import cargar_funciones_iniciales, leer_funciones
from asientos import inicializar_asientos
from utilidades import titulo_filmoteca

# Módulos
from usuarios import registrar_usuario
from reservas import registrar_reserva
from cancelar import cancelar_reserva
from cartelera import mostrar_cartelera
from administrador import admin


# ------------------------------------------------------------
#  PROGRAMA PRINCIPAL
# ------------------------------------------------------------
def main():
    # Archivos básicos
    asegurar_archivos()

    # Funciones iniciales
    cargar_funciones_iniciales()

    # Inicializar asientos para cada función
    for f in leer_funciones():
        inicializar_asientos(f["function_id"], f["disponibles"])

    # Bucle principal
    while True:
        titulo_filmoteca()

        print("1. Registrar Usuario")
        print("2. Registrar Reserva")
        print("3. Cancelar Reserva")
        print("4. Consultar Funciones")
        print("5. Administrador")
        print("6. Salir")

        opcion = input("\nSeleccione una opción: ")

        if opcion == "1":
            registrar_usuario()
        elif opcion == "2":
            registrar_reserva()
        elif opcion == "3":
            cancelar_reserva()
        elif opcion == "4":
            mostrar_cartelera()
        elif opcion == "5":
            admin()
        elif opcion == "6":
            print("\nGracias por usar Filmoteca 121 UdeA 💚\n")
            break
        else:
            print("Opción inválida.")

        input("\nPresione ENTER para continuar...")


# Ejecutar programa
if __name__ == "__main__":
    main()