# -*- coding: utf-8 -*-
"""reservas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g488IU6rM3s05fKdSlCArEqH8HMSYaPx

Reservas
"""

# ============================================================
#  MÓDULO DE RESERVAS
# ============================================================

import csv
import uuid
from datetime import datetime

from datos import RES_FILE, TARIFAS
from usuarios import buscar_usuario
from funciones import leer_funciones
from cartelera import mostrar_cartelera
from asientos import cargar_asientos, guardar_asientos, mostrar_asientos


# ------------------------------------------------------------
#  LEER RESERVAS
# ------------------------------------------------------------
def leer_reservas():
    """Retorna todas las reservas registradas."""
    with open(RES_FILE, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


# ------------------------------------------------------------
#  REGISTRAR UNA RESERVA
# ------------------------------------------------------------
def registrar_reserva():
    print("\n=== REGISTRAR RESERVA ===")

    doc = input("Documento del usuario: ").strip()
    user = buscar_usuario(doc)

    if not user:
        print("⚠️ Usuario no registrado.")
        return

    # Mostrar cartelera
    mostrar_cartelera()
    fid = input("\nIngrese ID de función (Ej: F01): ").strip().upper()

    # Mostrar mapa de asientos
    mostrar_asientos(fid)
    asiento = input("\nSeleccione asiento (Ej: A7): ").upper()

    # Cargar estado actual
    mapa = cargar_asientos(fid)
    sel = next((s for s in mapa if s["asiento"] == asiento), None)

    if not sel:
        print("Asiento inválido.")
        return

    if sel["estado"] == "X":
        print("Asiento ocupado.")
        return

    # Marcar como ocupado
    sel["estado"] = "X"
    guardar_asientos(fid, mapa)

    # Generar valores de factura
    precio = TARIFAS[user["vinculo"]]
    rid = str(uuid.uuid4())[:8]
    fecha = datetime.now().isoformat()

    # Guardar reserva en CSV
    with open(RES_FILE, "a", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow([rid, doc, fid, asiento, precio, fecha])

    # Imprimir factura
    print("\n===== FACTURA =====")
    print("Reserva:", rid)
    print("Usuario:", user["nombre"], user["apellido"])
    print("Función:", fid)
    print("Asiento:", asiento)
    print("Valor pagado: $", precio)
    print("----------------------------")