# -*- coding: utf-8 -*-
"""reservas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y9B6IkfkPZTMQ7FbEoCPJdS9lzURc-q2
"""
USERS_FILE = "users.csv"
RES_FILE = "reservas.csv"
FUNC_FILE = "funciones.csv"

import csv
from datetime import datetime
import uuid

# ============================================================
# IMPORTS
# ============================================================

# usuarios.py
from usuarios import buscar_usuario

# funciones.py
from funciones import mostrar_cartelera, leer_funciones

# asientos.py
from asientos import (
    inicializar_asientos,
    mostrar_asientos,
    cargar_asientos,
    guardar_asientos
)

# validaciones.py
from validaciones import TARIFAS, solicitar_documento_input


# ============================================================
# RESERVAS
# ============================================================

def leer_reservas():
    with open(RES_FILE, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def registrar_reserva():
    print("\n=== REGISTRAR RESERVA ===")

    # documento validado
    doc = solicitar_documento_input("Documento del usuario: ")

    user = buscar_usuario(doc)
    if not user:
        print("⚠️ Usuario no registrado.")
        return

    # Mostrar cartelera y pedir función
    mostrar_cartelera()
    fid = input("\nIngrese ID de función (Ej: F01): ").strip().upper()

    # Verificar que la función exista y obtener disponibilidad
    funcs = leer_funciones()
    func = next((f for f in funcs if f["function_id"] == fid), None)
    if not func:
        print("⚠️ ID de función inválido.")
        return

    # Inicializar asientos (si no existen)
    inicializar_asientos(fid, func["disponibles"])

    # Mostrar mapa
    mostrar_asientos(fid)
    mapa = cargar_asientos(fid)

    # Selección de asiento
    while True:
        asiento = input("\nSeleccione asiento (Ej: A7): ").strip().upper()
        sel = next((s for s in mapa if s["asiento"] == asiento), None)

        if not sel:
            print("❌ Asiento inválido.")
            continue

        if sel["estado"] == "X":
            print("❌ Ese asiento está ocupado. Elija otro.")
            continue

        sel["estado"] = "X"
        break

    # Guardar cambios en asientos
    guardar_asientos(fid, mapa)

    # Precio según vínculo del usuario
    precio = TARIFAS[user["vinculo"]]

    # ID reserva único
    rid = str(uuid.uuid4())[:8]
    fecha = datetime.now().isoformat()

    # Guardar reserva
    with open(RES_FILE, "a", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow([rid, doc, fid, asiento, precio, fecha])

    print("\n===== FACTURA =====")
    print("Reserva ID:", rid)
    print("Usuario:", user["nombre"], user["apellido"])
    print("Función:", fid)
    print("Asiento:", asiento)
    print("Valor pagado: $", precio)
    print("----------------------------")


def cancelar_reserva():
    print("\n=== CANCELAR RESERVA ===")

    doc = solicitar_documento_input("Documento del usuario: ")
    reservas = leer_reservas()
    mis_res = [r for r in reservas if r["documento"] == doc]

    if not mis_res:
        print("Este usuario no tiene reservas.")
        return

    print("\nN° | Función | Asiento | ID Reserva")
    print("---------------------------------------------")
    for i, r in enumerate(mis_res, 1):
        print(f"{i} | {r['function_id']} | {r['asiento']} | {r['idreserva']}")

    opcion = input("\nSeleccione número a cancelar: ").strip()

    if not opcion.isdigit():
        print("Opción inválida.")
        return

    opcion = int(opcion)
    if opcion < 1 or opcion > len(mis_res):
        print("Número inválido.")
        return

    target = mis_res[opcion - 1]

    # Liberar asiento
    mapa = cargar_asientos(target["function_id"])
    for s in mapa:
        if s["asiento"] == target["asiento"]:
            s["estado"] = "O"
    guardar_asientos(target["function_id"], mapa)

    # Reescribir archivo
    nuevas = [r for r in reservas if r["idreserva"] != target["idreserva"]]
    with open(RES_FILE, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=["idreserva", "documento", "function_id", "asiento", "precio", "fecha"])
        w.writeheader()
        w.writerows(nuevas)

    print("\n✔ Reserva cancelada exitosamente.")
