# -*- coding: utf-8 -*-
"""usuarios

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xO6RvuBXgjxqEbdy7qZjlo5hEBcUwUAd
"""

import csv
from datos import USERS_FILE, VINCULOS, TARIFAS
from utilidades import validar_nombre, solicitar_documento_input

def leer_usuarios():
    with open(USERS_FILE, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))

def buscar_usuario(doc):
    return next((u for u in leer_usuarios() if u["documento"] == doc), None)

def registrar_usuario():
    print("\n=== REGISTRO DE USUARIO ===")
    nombre = input("Nombre: ").strip()
    apellido = input("Apellido: ").strip()
    documento = solicitar_documento_input("Documento (solo números): ")

    print("\nTipos de vínculo:")
    for i, v in enumerate(VINCULOS, 1):
        print(f"{i}. {v} → ${TARIFAS[v]}")

    while True:
        sel = input("Seleccione el número del vínculo: ").strip()
        if sel.isdigit() and 1 <= int(sel) <= len(VINCULOS):
            vinculo = VINCULOS[int(sel) - 1]
            break
        print("❌ Selección inválida.")

    errores = validar_nombre(nombre)
    errores += validar_nombre(apellido)

    if buscar_usuario(documento):
        errores.append("El documento ya existe.")

    if errores:
        print("\n⚠️ Errores encontrados:")
        for e in errores:
            print(" -", e)
        return

    with open(USERS_FILE, "a", newline="", encoding="utf-8") as f:
        csv.writer(f).writerow([documento, nombre, apellido, vinculo])

    print("\n✔ Usuario registrado correctamente.")