# -*- coding: utf-8 -*-
"""usuarios

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xO6RvuBXgjxqEbdy7qZjlo5hEBcUwUAd
"""

# ============================================================
#  USUARIOS
# ============================================================

def leer_usuarios():
    with open(USERS_FILE, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))

def buscar_usuario(doc):
    return next((u for u in leer_usuarios() if u["documento"] == doc), None)

def registrar_usuario():
    print("\n=== REGISTRO DE USUARIO ===")
    nombre = input("Nombre: ").strip()
    apellido = input("Apellido: ").strip()

    # Documento validado
    documento = solicitar_documento_input("Documento (solo números): ")

    # Mostrar opciones numeradas de vínculo
    print("\nTipos de vínculo (escriba el número de la opción):")
    for i, v in enumerate(VINCULOS, start=1):
        print(f" {i}. {v}  → ${TARIFAS[v]}")

    # Selección por número
    while True:
        sel = input("\nSeleccione el número exacto del vínculo: ").strip()
        if not sel.isdigit():
            print("❌ Debe ingresar el número de la opción. Intente de nuevo.")
            continue
        idx = int(sel) - 1
        if idx < 0 or idx >= len(VINCULOS):
            print("❌ Opción inválida. Seleccione un número dentro del rango.")
            continue
        vinculo = VINCULOS[idx]
        break

    # Validaciones de nombre y apellido
    errores = validar_nombre(nombre)
    errores += validar_nombre(apellido)

    # Verificar si documento ya existe
    if buscar_usuario(documento):
        errores.append("El documento ya existe.")

    if errores:
        print("\n⚠️ Errores encontrados:")
        for e in errores:
            print(" -", e)
        return

    # Guardar usuario
    with open(USERS_FILE, "a", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow([documento, nombre, apellido, vinculo])

    print("\n✔ Usuario registrado correctamente.")