# -*- coding: utf-8 -*-
"""Usuarios

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g488IU6rM3s05fKdSlCArEqH8HMSYaPx

Usuarios
"""

# ============================================================
#  MÓDULO DE USUARIOS
# ============================================================

import csv
from datos import USERS_FILE, TARIFAS
from utilidades import validar_nombre, validar_documento


# ------------------------------------------------------------
#  LECTURA DE USUARIOS
# ------------------------------------------------------------
def leer_usuarios():
    """Lee todos los usuarios del archivo CSV."""
    with open(USERS_FILE, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def buscar_usuario(doc):
    """Busca un usuario por documento."""
    return next((u for u in leer_usuarios() if u["documento"] == doc), None)


# ------------------------------------------------------------
#  REGISTRO DE USUARIO
# ------------------------------------------------------------
def registrar_usuario():
    print("\n=== REGISTRO DE USUARIO ===")

    nombre = input("Nombre: ").strip()
    apellido = input("Apellido: ").strip()
    documento = input("Documento: ").strip()

    print("\nTipos de vínculo:")
    for v in TARIFAS:
        print(" -", v)

    vinculo = input("\nVínculo exacto: ").strip()

    # Validaciones
    errores = validar_nombre(nombre)
    errores += validar_nombre(apellido)
    errores += validar_documento(documento)

    if vinculo not in TARIFAS:
        errores.append("Vínculo inválido.")

    # Verificar duplicado
    if buscar_usuario(documento):
        errores.append("El documento ya existe.")

    if errores:
        print("\n⚠️ Errores encontrados:")
        for e in errores:
            print(" -", e)
        return

    # Registrar en archivo
    with open(USERS_FILE, "a", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow([documento, nombre, apellido, vinculo])

    print("\n✔ Usuario registrado correctamente.")