# -*- coding: utf-8 -*-
"""Utilidades

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g488IU6rM3s05fKdSlCArEqH8HMSYaPx

Utilidades
"""

# ============================================================
#  UTILIDADES GENERALES DEL SISTEMA
# ============================================================

import re

# ------------------------------------------------------------
#  TÍTULO EN VERDE PARA TODAS LAS PANTALLAS
# ------------------------------------------------------------
def titulo_filmoteca():
    VERDE = "\033[92m"
    RESET = "\033[0m"

    titulo = r"""
███████╗██╗██╗     ███╗   ███╗ ██████╗ ████████╗███████╗ ██████╗ █████╗      ██╗██████╗  ██╗
██╔════╝██║██║     ████╗ ████║██╔═══██╗╚══██╔══╝██╔════╝██╔════╝██╔══██╗    ███║╚════██╗███║
█████╗  ██║██║     ██╔████╔██║██║   ██║   ██║   █████╗  ██║     ███████║    ╚██║ █████╔╝╚██║
██╔══╝  ██║██║     ██║╚██╔╝██║██║   ██║   ██║   ██╔══╝  ██║     ██╔══██║     ██║██╔═══╝  ██║
██║     ██║███████╗██║ ╚═╝ ██║╚██████╔╝   ██║   ███████╗╚██████╗██║  ██║     ██║███████╗ ██║
╚═╝     ╚═╝╚══════╝╚═╝     ╚═╝ ╚═════╝    ╚═╝   ╚══════╝ ╚═════╝╚═╝  ╚═╝     ╚═╝╚══════╝ ╚═╝
    """

    print(VERDE + titulo + RESET)
    print("              Bienvenido a la Filmoteca 121 UdeA")
    print("              ------------------------------------\n")

# ------------------------------------------------------------
#  VALIDACIONES DE NOMBRE, APELLIDO Y DOCUMENTO
# ------------------------------------------------------------

def validar_nombre(txt):
    errores = []
    if len(txt) < 3:
        errores.append("Debe tener mínimo 3 letras.")
    if re.search(r"[0-9]", txt):
        errores.append("No puede tener números.")
    return errores

def validar_documento(doc):
    errores = []
    if not doc.isdigit():
        errores.append("Solo se permiten números.")
    if not (3 <= len(doc) <= 15):
        errores.append("Debe tener entre 3 y 15 dígitos.")
    return errores