# -*- coding: utf-8 -*-
"""validaciones

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y9B6IkfkPZTMQ7FbEoCPJdS9lzURc-q2
"""



import re

def validar_nombre(txt):
    errores = []
    if len(txt) < 3:
        errores.append("Debe tener mínimo 3 letras.")
    if re.search(r"[0-9]", txt):
        errores.append("No puede tener números.")
    return errores

def validar_documento(doc):
    errores = []
    if not doc.isdigit():
        errores.append("Solo se permiten números.")
    if not (3 <= len(doc) <= 15):
        errores.append("Debe tener entre 3 y 15 dígitos.")
    return errores
    
def solicitar_documento_input(mensaje):
    while True:
        doc = input(mensaje).strip()
        errores = validar_documento(doc)
        if errores:
            print("⚠️ Error en el documento:")
            for e in errores:
                print(" -", e)
            continue
        return doc

# Tarifas por tipo de vínculo
TARIFAS = {
    "Estudiantes": 7500,
    "Docentes": 10000,
    "Administrativos": 8500,
    "Oficiales internos": 7000,
    "Publico externo": 15000
}

VINCULOS = list(TARIFAS.keys())
